config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  root to: "top#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets, :users_comments
      get "users_favorites" => "favorites#users_favorites"
      get "users_clips" => "clips#users_clips"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :artists do
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
  end
  resources :favorites, only: [:destroy, :index]
  resources :events do
    member do
      post "add", to: "clips#create"
      get "show_clips" => "clips#show_clips"
    end
  end
  resources :clips, only: [:destroy, :index]
  resources :groups, only: [:show, :edit, :update, :destroy]
  get "show_tweets" => "tweets#show_tweets"
  get "show_comments" => "tweets#show_comments"
  get "following_tweets" => "tweets#following_tweets"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'
end

app/models/clip.rb
class Clip < ActiveRecord::Base

  validates :user_id, :uniqueness => {:scope => :event_id}

    belongs_to :user
    belongs_to :event
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def create


    @user_id = current_user.id
    @event_id = Event.find(params[:id]).id
    @clip = Clip.new(event_id: @event_id, user_id: @user_id)

    if @clip.save
      redirect_to clips_path(current_user)
    else
      redirect_to clips_path(current_user)
    end

  end

  def destroy
    @clip = Clip.find(params[:id])
    if @clip.destroy
      redirect_to clips_path(current_user)
    end
  end

  def index
    @user = current_user
    @count = Clip.where(user_id: @user.id).all
    @clips = Clip.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  def show_clips
    @event = Event.find(params[:id])
    @count = Clip.where(event_id: @event.id).all
    @clips = Clip.where(event_id: @event.id).all.order("RANDOM()").page(params[:page]).per(20)
  end

  def users_clips
    @user = User.find(params[:id])
    @count = Clip.where(user_id: @user.id).all
    @clips = Clip.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(20)
  end

end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/index.html.erb
<% if user_signed_in? %>
<div class="row">
  <h2>参加中のイベント</h2>
  <span class="name4">参加中のイベント数 :<%=@count.length %></span><br/>
  <%= link_to "イベント検索", events_path, {class: 'btn btn-primary withripple' } %>
  <br/>
    <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>

<br/>

    <% @clips.each do |clip| %>
      <% event = Event.find(clip.event_id) %>
          <tr>
            <div class="name3"><%= link_to event.event_name, event_path(event) %></div>
            <div class="name2"><%= link_to "参加中のイベントから削除",clip_path(clip), method: :delete %></div>
              <div class="name2">
            <%= event.event_date.strftime("%Y-%m-%d %H:%M:%S")  %>
            </div>
            <div class="name2">
            <%= event.event_location %>
            </div>
        </tr>
    <br />
    <% end %>
    <%= paginate(@clips) %>
</div>
<% end %>

app/views/clips/show_clips.html.erb
<h2>イベント参加中のユーザー&nbsp;&nbsp;<%= @count.length %>人</h2>
  <div class="name4">
    <%= link_to @event.event_name, event_path(@event) %>
    <div class="name2">
      <% @artist_id = @event.artist_id %>
      <% @artist = Artist.where(id: @artist_id).first %>
      出演アーティスト:<%= link_to @artist.artist_name,artist_path(@artist) %>
      </div>
    <% if user_signed_in? %>
    <% if current_user.id == @event.user_id %>
    <div class="name2">
    <%= link_to "このイベントを削除", "/events/#{@event.id}", method: :delete %>
    </div>
    <div class="name2">
    <%= link_to "編集", edit_event_path, method: :get %>
    </div>
    <% end %>
    <% end %>
    <%= @event.event_date.strftime("%Y-%m-%d %H:%M:%S") %>
    <p><%= @event.event_location %></p>
    <% if user_signed_in? %>
    <div class="name2">
    <%= link_to "このイベントに参加", add_event_path(@event), method: :post %>
    </div>
    <% end %>
  </div>
  <br/>

    <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

  <h2>ユーザー一覧&nbsp;&nbsp;(<%= @count.length %>人)</h2>

    <% @clips.each do |clip| %>
      <% @user_id = clip.user_id %>
      <% user = User.find(@user_id) %>
      <div class ="name2">&nbsp;</div>
      <div class="user_avatars">
        <%= link_to user.username ,user_path(user) %><br/>
        <span><img src="<%= user.avatar.url(:thumb) %>"></span><br />

        <span class = "name2">
        <% if user.gender == "male" %>&nbsp;&nbsp;男性
        <% elsif user.gender == "female" %>&nbsp;&nbsp;女性
        <% else %>
        <% end %>
        <% if user.birthday? %>
        <% date_format = "%Y%m%d" %>
        <% @age = (Date.today.strftime(date_format).to_i - user.birthday.strftime(date_format).to_i) / 10000 %>
        &nbsp;&nbsp;<%= @age %>歳<br/>
        <% end %>
        <% if user.location? %>
        &nbsp;&nbsp;(<%= user.location %>)
        <% end %>
      </span>
      </div>
      <br/>
    <% end %>
<%= paginate(@clips) %>
  </div>

app/views/clips/users_clips.html.erb
<div class="row">
  <h2><%= link_to @user.username, user_path(@user) %>の参加中のイベント</h2>
  <span class="name4">参加中のイベント数 :<%=@count.length %></span><br/>
  <%= link_to "イベント検索", events_path, {class: 'btn btn-primary withripple' } %>
  <br/>
    <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

    <% @clips.each do |clip| %>
      <% event = Event.find(clip.event_id) %>
          <tr>
            <div class="name3"><%= link_to event.event_name, event_path(event) %></div>
            <div class="name2"><%= link_to "参加中のイベントから削除",clip_path(clip), method: :delete %></div>
              <div class="name2">
            <%= event.event_date.strftime("%Y-%m-%d %H:%M:%S")  %>
            </div>
            <div class="name2">
            <%= event.event_location %>
            </div>
        </tr>
    <br />
    <% end %>
    <%= paginate(@clips) %>
</div>