config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  root to: "top#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets, :users_comments
      get "users_favorites" => "favorites#users_favorites"
      get "users_clips" => "clips#users_clips"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :artists do
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
  end
  resources :favorites, only: [:destroy, :index]
  resources :events do
    member do
      post "add", to: "clips#create"
      get "show_clips" => "clips#show_clips"
    end
  end
  resources :clips, only: [:destroy, :index]
  resources :groups, only: [:show, :edit, :update, :destroy]
  get "show_tweets" => "tweets#show_tweets"
  get "show_comments" => "tweets#show_comments"
  get "following_tweets" => "tweets#following_tweets"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @user = current_user
    @search = Tweet.search(params[:q])
    @tweets = @search.result.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @tweet =Tweet.new
  end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params) if tweet.user_id == current_user.id
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  def show_tweets
    @user = current_user
    @tweets = Tweet.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  def show_comments
    @user = current_user
    @comments = Comment.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  def following_tweets
    @user = current_user
    @users = @user.followings.order("created_at DESC").page(params[:page]).per(20)
  end

  private
  def tweet_params
    params.permit(:text)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/create.html.erb
<% if user_signed_in? %>
<div class="contents row">
    <div class="success">
      <h2>
        投稿が完了しました。
      </h2>
      <%= link_to '投稿一覧へ戻る', tweets_path, {class: 'btn btn-primary withripple' }%>
    </div>
</div>
<% end %>

app/views/tweets/destroy.html.erb
<% if user_signed_in? %>
  <div class="contents row">
    <div class="success">
      <h2>
        削除が完了しました。
      </h2>
      <%= link_to '投稿一覧へ戻る', tweets_path, {class: 'btn btn-primary withripple' }%>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<% if user_signed_in? %>
  <div class="contents row">
    <%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
      <h2>
        編集する
      </h2>
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text %></textarea>
      <br/>
      <input type="submit" value="変更する">
    <% end %>
  </div>
<% end %>

app/views/tweets/following_tweets.html.erb
<% if user_signed_in? %>
<h2>フォロー中のツイート</h2>
<% @users.each do |user| %>
  <% @tweets = Tweet.where(user_id: user.id).limit(1).order("created_at DESC") %>
  <% @tweets.each do |tweet| %>
    <div class="contents row" >
      <div class="name4"><img src="<%= tweet.user.avatar.url(:thumb) %>"><%= link_to user.username, user_path(user), method: :get %>&nbsp;&nbsp;<br/><%= link_to 'ツイート一覧へ', users_tweets_user_path(user), {class: 'btn btn-primary withripple' }%></div>
      <div class="name2"><%= tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
      <div class="name2"><%= link_to '詳細', tweet_path(tweet), method: :get %></div>
      <div class="name4"><%= simple_format(tweet.text) %></div>
    </div>
    <br/>
  <% end %>

  <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

<% end %>
  <%= paginate(@users) %>
</div>
<% end %>

app/views/tweets/index.html.erb
<h2>ツイート検索</h2>
<div>
    <%= search_form_for @search do |f| %>
    <%= f.label :text_cont, '🔎' %>
    <%= f.text_field :text_cont %>
    <%= f.submit '検索' %>&nbsp;&nbsp;<%= link_to ">>ユーザーから検索", users_path %>
    <br/>
    <span class = "name2">※キーワードから検索いただけます。</span>
    <br />
    <%= link_to '検索条件のクリア', request.path %>
    </div>
    <% end %>
<% if user_signed_in? %>
<%= link_to '　　ツイートを投稿する　　', new_tweet_path, {class: 'btn btn-primary withripple' }%><br/>
<%= link_to '　自分のツイート一覧へ　　', show_tweets_path, {class: 'btn btn-primary withripple' }%><br/>
<%= link_to 'フォロー中のツイート一覧へ', following_tweets_path, {class: 'btn btn-primary withripple' }%><br/>
<% end %>
<br/>

<script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

<% @tweets.each do |tweet| %>
    <div class="contents row" >
      <div class="name4"><img src="<%= tweet.user.avatar.url(:thumb) %>"><%= link_to tweet.user.username, user_path(tweet.user), method: :get %>
      <div class="name2"><%= tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
      <div class="name2"><%= link_to '詳細', tweet_path(tweet), method: :get %></div>
      <div class="name4"><%= simple_format(tweet.text) %></div>
    </div>
    </div>
<% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<% if user_signed_in? %>
<div class="contents row">
    <%= form_tag('/tweets', method: :post) do %>
      <h2>
        投稿する
      </h2>
      <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
      <br/>
      <input type="submit" value="投稿する">
    <% end %>
</div>
<% end %>

app/views/tweets/show.html.erb
<h2>投稿</h2>
<div class="contents row" >
      <div class="name4"><img src="<%= @tweet.user.avatar.url(:thumb) %>"><%= link_to @tweet.user.username, user_path(@tweet.user), method: :get %></div>
      <div class="name2"><%= @tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
    <% if user_signed_in? %>
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="name2">
       <%= link_to '編集', edit_tweet_path(@tweet), method: :get %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
      </div>
      <% end %>
    <% end %>
      <div class="name4"><%= simple_format(@tweet.text) %></div>
</div>
  <br/>

    <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":702492,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

<div class="contents row" >
<h2>コメント一覧</h2>
      <% if @comments %>
        <% @comments.each do |comment| %>
        <div class="name2"><img src="<%= comment.user.avatar.url(:thumb) %>"><%= link_to comment.user.username, "/users/#{comment.user_id}" %><br/><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
        <div class="name2"><%= comment.text %></div>
         <% if user_signed_in? %>
          <% if comment.user_id == current_user.id %>
          <div class="name2">
          <%= link_to '削除', "/tweets/#{comment.tweet_id}/comments/#{comment.id}", method: :delete %>
          </div>
          <% end %>
         <% end %>
        <% end %>
      <% end %>
<br/>
<% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <br/>
        <input type="submit" value="コメントの投稿">
      <% end %>
<% end %>
    </div>

app/views/tweets/show_comments.html.erb
<% if user_signed_in? %>
<h2>自分のコメント一覧</h2>
<% if @comments %>
        <% @comments.each do |comment| %>
        <div class="name2"><%= link_to comment.tweet.user.username, user_path(comment.tweet.user) %>さんのツイートにコメント</div>
        <div class="name2"><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
        <div class="name2"><%= comment.text %></div>
        <div class="name2"><%= link_to '詳細', tweet_path(comment.tweet_id), method: :get %></div>
        <br/>

<script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>
        <% end %>
      <% end %>
  <%= paginate(@comments) %>
</div>
<% end %>

app/views/tweets/show_tweets.html.erb
<% if user_signed_in? %>
<h2>自分のツイート一覧</h2>
<%= link_to 'ツイートを投稿する', new_tweet_path, {class: 'btn btn-primary withripple' }%>
<%= link_to '自分のコメント一覧', show_comments_path(current_user), {class: 'btn btn-primary withripple' }%>
<% @tweets.each do |tweet| %>
    <div class="contents row" >
      <div class="name2"><%= tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
      <div class="name2"><%= link_to '詳細', tweet_path(tweet), method: :get %></div>
      <div class="name4"><%= simple_format(tweet.text) %></div>
    </div>
    <br/>

<script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

<% end %>
  <%= paginate(@tweets) %>
</div>
<% end %>

app/views/tweets/update.html.erb
<% if user_signed_in? %>
  <div class="contents row">
    <div class="success">
      <h2>
        更新が完了しました。
      </h2>
      <%= link_to '投稿一覧へ戻る', tweets_path, {class: 'btn btn-primary withripple' }%>
    </div>
  </div>
<% end %>