config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  root to: "top#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets, :users_comments
      get "users_favorites" => "favorites#users_favorites"
      get "users_clips" => "clips#users_clips"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :artists do
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
  end
  resources :favorites, only: [:destroy, :index]
  resources :events do
    member do
      post "add", to: "clips#create"
      get "show_clips" => "clips#show_clips"
    end
  end
  resources :clips, only: [:destroy, :index]
  resources :groups, only: [:show, :edit, :update, :destroy]
  get "show_tweets" => "tweets#show_tweets"
  get "show_comments" => "tweets#show_comments"
  get "following_tweets" => "tweets#following_tweets"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(username:     auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  # def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
  #   user = User.where(:provider => auth.provider, :uid => auth.uid).first
  #   unless user
  #     user = User.create(name:     auth.info.nickname,
  #                        provider: auth.provider,
  #                        uid:      auth.uid,
  #                        email:    User.create_unique_email,
  #                        password: Devise.friendly_token[0,20]
  #                       )
  #   end
  #   user
  # end


  def self.create_unique_string
    SecureRandom.uuid
  end


  # def self.create_unique_email
  #   User.create_unique_string + "@example.com"
  # end

  if Rails.env.production?
    S3_CREDENTIALS={access_key_id: "", secret_access_key: "", bucket:"", s3_host_name: ""}
  end

  if Rails.env.production?
  has_attached_file :avatar, storage: :s3, s3_credentials: S3_CREDENTIALS,
  styles: { medium: "300x300!", thumb: "100x100!>"}, path:":attachment/:id/:style.:extension"
  else
    has_attached_file :avatar, styles: { medium: "300x300!", thumb: "100x100!>"}
  end

  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png","image/gif"],message: 'ファイル形式が不正です。ipg,jpeg,png,gifのいずれかのファイルで再度お試しください。'


  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
  end

  #association
  has_many :favorites
  has_many :clips
  has_many :artists, through: :favorites
  has_many :events, through: :clips
  has_many :groups
  has_many :tweets
  has_many :comments

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  # def twitter
  #   # You need to implement the method below in your model
  #   @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

  #   if @user.persisted?
  #     set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
  #     sign_in_and_redirect @user, :event => :authentication
  #   else
  #     session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
  #     redirect_to new_user_registration_url
  #   end
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @search = User.search(params[:q])
    @users = @search.result.order("RANDOM()").page(params[:page]).per(20)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.birthday?
    date_format = "%Y%m%d"
    @age = (Date.today.strftime(date_format).to_i - @user.birthday.strftime(date_format).to_i) / 10000
    end
    @favorites = Favorite.where(user_id: @user.id).limit(10).order("RANDOM()")
    @clips = Clip.where(user_id: @user.id).limit(10).order("created_at DESC")
    @tweets = Tweet.where(user_id: @user.id).limit(5).order("created_at DESC")
    @favorites_count = Favorite.where(user_id: @user.id).all
    @clips_count = Clip.where(user_id: @user.id).all
  end

  def edit
  end

  def update
    current_user.update(update_params)
  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def users_tweets
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  def users_comments
    @user = User.find(params[:id])
    @comments = Comment.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :avatar, :username, :gender, :location, :hometown, :birthday, :comment)
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.id == user.id %>
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow', user: user %>
  <% else %>
    <%= render 'users/follow', user: user %>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<% if user_signed_in? %>
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
      <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
          ユーザー名(2文字〜15文字)<%= f.text_field :username, placeholder: "ユーザー名(2文字〜15文字)", class: "form-control", :maxlength => "15" %>
      </div>
      <div class="form-group">
      氏名(※公開されません。)
        <div class="col-lg-6">
          姓<%= f.text_field :family_name, placeholder: "姓", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          名<%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          カナ<%= f.text_field :family_name_kana, placeholder: "セイ", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          カナ<%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">性別<br/>
          <label><%= f.radio_button :gender, "male" %>男性</label>
          <label><%= f.radio_button :gender, "female" %>女性</label>
      </div>
      <div class="form-group">
          居住地<%= f.text_field :location, placeholder: "居住地", class: "form-control" %>
      </div>
      <div class="form-group">
          出身地<%= f.text_field :hometown, placeholder: "出身地", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "生年月日" %><br/>
        <%= f.date_select(
          :birthday,
          use_month_numbers: true,
          start_year:     1930,
          end_year:       (Time.now.year - 18),
          default:        Date.new(1989, 1, 1),
          date_separator: '/') %>
        </div>
      <div class="form-group">
          ひとことプロフィール(100文字以内)<%= f.text_area :comment, placeholder: "100文字以内", :maxlength => "100" %>
      </div>
      <div class="form-group">
        <%= f.submit "更新", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
  <h2>ユーザー検索</h2>
  <div class="contents row" >
    <div>
    <%= search_form_for @search do |f| %>
    <%= f.label :username_or_family_name_or_first_name_or_family_name_kana_or_first_name_kana_or_location_cont, '🔎' %>
    <%= f.text_field :username_or_family_name_or_first_name_or_family_name_kana_or_first_name_kana_or_location_cont %>
    <%= f.submit '検索' %><br/>
    <span class = "name2">※ユーザー名、氏名、カナ名、居住地から検索可能です。</span>
    <br />
    <%= link_to '検索条件のクリア', request.path %>
    <% end %>
    </div>
<br/>

<script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

<br/>
    <% @users.each do |user| %>
    <div class ="name2">&nbsp;</div>
      <div class="user_avatars">
        <%= link_to user.username ,user_path(user) %><br/>
        <span><img src="<%= user.avatar.url(:thumb) %>"></span><br />

        <span class = "name2">
        <% if user.gender == "male" %>&nbsp;&nbsp;男性
        <% elsif user.gender == "female" %>&nbsp;&nbsp;女性
        <% else %>
        <% end %>
        <% if user.birthday? %>
        <% date_format = "%Y%m%d" %>
        <% @age = (Date.today.strftime(date_format).to_i - user.birthday.strftime(date_format).to_i) / 10000 %>
        &nbsp;&nbsp;<%= @age %>歳<br/>
        <% end %>
        <% if user.location? %>
        &nbsp;&nbsp;(<%= user.location %>)
        <% end %>
      </span>
      </div>
      <br/>
    <% end %>
<%= paginate(@users) %>
  </div>

app/views/users/show.html.erb
<div class="row form user_profile">
  <div class="col-lg-12">
    <div class="image" style="background-image: url(<%= @user.avatar.url(:medium) %>);"></div>
    <h4><%= @user.username %></h4>
    <% if @user.birthday? %>
    <h4><%= @age %>歳</h4>
    <% end %>
    <% if @user.gender == "male" %>
    <h4>男性</h4>
    <% elsif @user.gender == "female" %>
    <h4>女性</h4>
    <% else %>
    <% end %>
    <% if @user.location? %>
    <h4>居住地: <%= @user.location %></h4>
    <% end %>
    <% if @user.hometown? %>
    <h4>出身地: <%= @user.hometown %></h4>
    <% end %>
  <% if user_signed_in? %>
    <% if current_user.id == @user.id %>
      <div class="profile_edit">
        <%= link_to '編集', edit_user_path(current_user), {class: 'btn btn-primary withripple' }%>
      </div>
    <% end %>
  <% end %>
  </div>
  <span id="user_<%= @user.id %>" class="follow-wrapper">
      <%= render 'follow_form', user: @user if signed_in? %>
    </span>
  <h4>
    <%= render 'common/stats' %>
  </h4>
  <br/>
  <h4>プロフィール</h4>
  <div class = "name2"><%= simple_format(@user.comment) %></div>
</div>
<br/>

    <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":702492,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>


  <h2>ツイート一覧</h2>
  <%= link_to '全て見る', users_tweets_user_path(@user), {class: 'btn btn-primary withripple' }%>
      <% @tweets.each do |tweet| %>
      <Tr>
      <div class="name2"><%= tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
      <div class="name2"><%= link_to '詳細', tweet_path(tweet), method: :get %></div>
      <div class="name2"><%= simple_format(tweet.text) %></div>
    </Tr>
      <% end %>

  <h2>お気に入りのアーティスト: <%=@favorites_count.length %>組</h2>
    <%= link_to '全て見る', users_favorites_user_path(@user), {class: 'btn btn-primary withripple' }%>
    <% @favorites.each do |favorite| %>
      <% artist = Artist.find(favorite.artist_id) %>
          <tr>
            <div class="name2"><%= link_to artist.artist_name,artist_path(artist) %>
            </div>
          </tr>
    <% end %>
<br />

  <h2>参加中のイベント : <%=@clips_count.length %>件</h2>
  <%= link_to '全て見る', users_clips_user_path(@user), {class: 'btn btn-primary withripple' }%>
    <% @clips.each do |clip| %>
      <% event = Event.find(clip.event_id) %>
          <tr>
            <div class="name2"><%= link_to event.event_name,event_path(event) %>
              <div class="name2">
            <%= event.event_date.strftime("%Y-%m-%d %H:%M:%S") %>
            </div>
            <div class="name2">
            <%= event.event_location %>
            </div>
          </div>
        </tr>
        <br/>
    <% end %>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'common/stats' %>
    <h2><%= @title %></h2>
      <% if @users.any? %>
          <% @users.each do |user| %>
          <div class="user_avatars">
            <span><img src="<%= user.avatar.url(:thumb) %>"></span><br />
            <%= link_to user.username ,user_path(user) %>
          </div>
          <br/>

    <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":702492,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

          <% end %>
      <% end %>
    </section>
  </aside>
</div>

app/views/users/update.html.erb
<% if user_signed_in? %>
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "マイページへ戻る", user_path %>
  </div>
</div>
<% end %>

app/views/users/users_comments.html.erb
<h2><%= link_to @user.username,user_path(@user)%>のコメント一覧</h2>
<%= link_to 'ツイート一覧', users_tweets_user_path(@user), {class: 'btn btn-primary withripple' }%>
<% if @comments %>
        <% @comments.each do |comment| %>
        <div class="name2"><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
        <div class="name2"><%= comment.text %></div>
        <div class="name2"><%= link_to '詳細', tweet_path(comment.tweet_id), method: :get %></div>
            <br/>

  <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

        <% end %>
      <% end %>
  <%= paginate(@comments) %>
</div>

app/views/users/users_tweets.html.erb
<h2><%= link_to @user.username,user_path(@user)%>のツイート一覧</h2>

<%= link_to 'コメント一覧', users_comments_user_path(@user), {class: 'btn btn-primary withripple' }%>
<% @tweets.each do |tweet| %>
    <div class="contents row" >
      <div class="name2">投稿日時:<%= tweet.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
      <div class="name2"><%= link_to '詳細', tweet_path(tweet), method: :get %></div>
      <div class="name4"><%= simple_format(tweet.text) %></div>
    </div>
    <br/>

  <script type="text/javascript">
var nend_params = {"media":43808,"site":243648,"spot":701028,"type":1,"oriented":1};
</script>
<script type="text/javascript" src="https://js1.nend.net/js/nendAdLoader.js"></script>
<br/>

<% end %>
  <%= paginate(@tweets) %>
</div>