config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {
  :sessions      => "users/sessions",
  :registrations => "users/registrations",
  :passwords     => "users/passwords",
  :omniauth_callbacks => "users/omniauth_callbacks"
}

  root to: "top#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets, :users_comments
      get "users_favorites" => "favorites#users_favorites"
      get "users_clips" => "clips#users_clips"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :artists do
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
  end
  resources :favorites, only: [:destroy, :index]
  resources :events do
    member do
      post "add", to: "clips#create"
      get "show_clips" => "clips#show_clips"
    end
  end
  resources :clips, only: [:destroy, :index]
  resources :groups, only: [:show, :edit, :update, :destroy]
  get "show_tweets" => "tweets#show_tweets"
  get "show_comments" => "tweets#show_comments"
  get "following_tweets" => "tweets#following_tweets"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'
end

app/models/artist.rb
class Artist < ActiveRecord::Base

  validates :artist_name, presence: true, uniqueness: true
  validates :artist_name_japanese, presence: true
  validates :artist_image_url, presence: true
  validates :artist_url, presence: true, uniqueness: true

  #assosiation
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :events, dependent: :nullify
  has_many :groups
end

app/models/clip.rb
class Clip < ActiveRecord::Base

  validates :user_id, :uniqueness => {:scope => :event_id}

    belongs_to :user
    belongs_to :event
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :event_name, presence: true
  validates :event_location, presence: true
  validates :event_date, presence: true

  #association
  # has_many :artists
  belongs_to :artist
  has_many :clips, dependent: :destroy
  has_many :users, through: :clips
  has_many :groups
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  validates :user_id, :uniqueness => {:scope => :artist_id}

    belongs_to :user
    belongs_to :artist
end

app/models/group.rb
class Group < ActiveRecord::Base

  #association
  belongs_to :artist
  has_many :users
  belongs_to :event

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(username:     auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  # def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
  #   user = User.where(:provider => auth.provider, :uid => auth.uid).first
  #   unless user
  #     user = User.create(name:     auth.info.nickname,
  #                        provider: auth.provider,
  #                        uid:      auth.uid,
  #                        email:    User.create_unique_email,
  #                        password: Devise.friendly_token[0,20]
  #                       )
  #   end
  #   user
  # end


  def self.create_unique_string
    SecureRandom.uuid
  end


  # def self.create_unique_email
  #   User.create_unique_string + "@example.com"
  # end

  if Rails.env.production?
    S3_CREDENTIALS={access_key_id: "", secret_access_key: "", bucket:"", s3_host_name: ""}
  end

  if Rails.env.production?
  has_attached_file :avatar, storage: :s3, s3_credentials: S3_CREDENTIALS,
  styles: { medium: "300x300!", thumb: "100x100!>"}, path:":attachment/:id/:style.:extension"
  else
    has_attached_file :avatar, styles: { medium: "300x300!", thumb: "100x100!>"}
  end

  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png","image/gif"],message: 'ファイル形式が不正です。ipg,jpeg,png,gifのいずれかのファイルで再度お試しください。'


  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
  end

  #association
  has_many :favorites
  has_many :clips
  has_many :artists, through: :favorites
  has_many :events, through: :clips
  has_many :groups
  has_many :tweets
  has_many :comments

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @artists = Artist.order("RANDOM()").limit(30)
    # @event = Event.order("RAND()").first
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/common/_header.html.erb
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>ライブ仲間と繋がろう！</small>
      <% end %>

      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
<!--           <li><%= link_to 'HOME', root_path %></li> -->

         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ユーザー<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
           <li><h7><%= link_to "ユーザー検索", users_path %></h7></li>
          </ul>
         </li>

         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ツイート<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
           <li><h7><%= link_to "ツイート検索", tweets_path %></h7></li>
           <% if user_signed_in? %>
           <li><h7><%= link_to "フォロー中ツイート", following_tweets_path %></h7></li>
           <li><h7><%= link_to "自分のツイート一覧", show_tweets_path %></h7></li>
           <li><h7><%= link_to "ツイート投稿", new_tweet_path %></h7></li>
           <% end %>
          </ul>
         </li>

         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">イベント<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
           <li><h7><%= link_to "イベント検索", events_path %></h7></li>
           <% if user_signed_in? %>
           <li><h7><%= link_to "参加中のイベント", clips_path %></h7></li>
           <% end %>
          </ul>
         </li>

         <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アーティスト <span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
           <li><h7><%= link_to "アーティスト検索", artists_path %></h7></li>
           <% if user_signed_in? %>
           <li><h7><%= link_to "お気に入り一覧", favorites_path %></h7></li>
           <% end %>
          </ul>
         </li>

         <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント<span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
          <% if user_signed_in? %>
           <li><h7><%= link_to "マイページ", user_path(current_user) %></h7></li>
           <li><h7><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></h7></li>
           <% else %>
           <li><h7><%= link_to "ログイン", user_session_path %></h7></li>
           <li><h7><%= link_to "新規ユーザー登録", new_user_registration_path %></h7></li>
           <% end %>
          </ul>
         </li>

        </ul>
      </div>
    </div>
  </div>

app/views/common/_login_logo.html.erb
<div class='sign_up_logo'>
  <%= image_tag 'logo.png' %>
  <small>ライブ仲間と繋がろう！</small>
</div>

app/views/common/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  &nbsp;<br/>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/common/error_artist.html.erb
<% if user_signed_in? %>
<div class="contents row">
      <h2>
        エラーが発生しました。
      </h2>
      <div class ="name2">
        1.入力必須項目に漏れはありませんか?<br/>
        <br/>
        2.アーティストの重複登録を防ぐため、すでに登録済みの「アーティスト名」または「アーティストURL」が入力された場合は登録ができません。
        <br/>「アーティスト名」が同一の別アーティストを登録する場合は入力形式を変更してお試しください。<br/>
        (例)アーティスト名:Circlepit → アーティスト名:Circlepit(Japan)
      </div>
      <%= link_to '新規アーティスト登録へ戻る', new_artist_path, {class: 'btn btn-primary withripple' }%>
</div>
<% end %>

app/views/common/error_event.html.erb
<% if user_signed_in? %>
<div class="contents row">
      <h2>
        エラーが発生しました。
      </h2>
      <div class ="name2">
      入力必須項目に漏れはありませんか?<br/>
      <%= link_to '新規イベント登録へ戻る', new_event_path, {class: 'btn btn-primary withripple' }%>
    </div>
</div>
<% end %>